plugins {
    id "com.android.application"
}

android {
    namespace "com.byw.roadofpoker"
    compileSdk 36

    defaultConfig {
        applicationId "com.byw.roadofpoker"
        minSdk 24
        targetSdk 36
        versionCode 4
        versionName "1.3.0"
    }

    buildTypes {
        debug {
            debuggable false
        }
        release {
            minifyEnabled false
        }
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}
